simplification of the deployment scripts to support both CE and EE deployments

diff --git a/swarm/conf b/swarm/conf
--- a/swarm/conf
+++ b/swarm/conf
@@ -1,17 +1,19 @@
+#!/bin/bash
 
-export STACK_NAME=$1
-if [ -z $STACK_NAME ]; then 
-  echo "No stack name specified! Stack name is required."
-  exit 1
-fi
-
-export DB_CONFIG=./deploys/$2
+export DB_CONFIG=./deploys/$1
 if [ ! -f $DB_CONFIG ]; then 
   echo "The galera yml config file was unspecified or not found in the 'deploys' folder."
   exit 1
 fi
 
+export STACK_NAME=`sed -n '/^stack-name:/ {s///p;q;}' $DB_CONFIG | xargs`
+if [ -z $STACK_NAME ]; then 
+  echo "No stack name specified! Stack name is required."
+  exit 1
+fi
+
 export DOCKER_HOST=`sed -n '/^docker-host:/ {s///p;q;}' $DB_CONFIG | xargs`
+export DOCKER_CERT_PATH=`sed -n '/^docker-host-cert-path:/ {s///p;q;}' $DB_CONFIG | xargs`
 export USE_VDVS=`sed -n '/^use-vdvs:/ {s///p;q;}' $DB_CONFIG | xargs`
 
 if [ "$USE_VDVS" != "true" ]; then
diff --git a/swarm/deploy b/swarm/deploy
--- a/swarm/deploy
+++ b/swarm/deploy
@@ -2,13 +2,13 @@
 
 function show_usage () {
   echo 
-  echo "Usage: deploy <stack name> <galera yml config file>"
+  echo "Usage: deploy <galera yml config file>"
   echo 
-  echo "Eg: deploy tier1 tier1-galera.yml"
+  echo "Eg: deploy tier1-galera.yml"
   echo 
 }
 
-source ./conf $1 $2
+source ./conf $1
 if [ $? -ne 0 ]; then
   show_usage
   exit 1
@@ -24,11 +24,13 @@ XTRABACKUP_PWD=` cat .secrets/xtrabackup_password`
 MYSQL_PWD=` cat .secrets/mysql_password`
 MYSQL_ROOT_PWD=` cat .secrets/mysql_root_password`
 
+echo "Deploying the cluster network: ${GALERA_NETWORK_NAME} ${GALERA_NETWORK} ..."
+./docker-env network create --driver overlay --subnet $GALERA_NETWORK $GALERA_NETWORK_NAME
+echo
+echo "Deploying the MariaDB Galera ${STACK_NAME} cluster..."
+
 export STACK_FOLDER=stacks
 
-echo
-echo "Deploying Galera Stack: ${STACK_NAME}"
-echo
 if [ "$USE_VDVS" == "true" ]; then
 
   echo "vDVS Data Volume Configuration:"
@@ -36,8 +38,10 @@ if [ "$USE_VDVS" == "true" ]; then
 
   HOST_NODE_VOL_SIZE=`sed -n '/^host-node-volume-size:/ {s///p;q;}' $DB_CONFIG | xargs`
   [ -z $HOST_NODE_VOL_SIZE ] && HOST_NODE_VOL_SIZE=128gb
-  HOST_NODE_DATASTORE=`sed -n '/^host-node-datastore:/ {s///p;q;}' $DB_CONFIG | xargs`
+  export HOST_NODE_DATASTORE=`sed -n '/^host-node-datastore:/ {s///p;q;}' $DB_CONFIG | xargs`
 
+  echo "Creating the ${HOST_NODE_VOL_SIZE} vDVS seed volume for the galera cluster ..."
+  ./docker-env volume create --driver=vsphere --name=${STACK_NAME}_galera-seed-volume@${HOST_NODE_DATASTORE} -o size=${HOST_NODE_VOL_SIZE}
   for i in `seq 1 3`
   do
     HOST_VOL_NAME=${STACK_NAME}_galera-node${i}-volume
@@ -45,13 +49,45 @@ if [ "$USE_VDVS" == "true" ]; then
       HOST_VOL_NAME=${HOST_VOL_NAME}@${HOST_NODE_DATASTORE}
     fi
     echo "Creating the ${HOST_NODE_VOL_SIZE} vDVS volume for the galera node ${i} ..."
-    ./docker-env volume create --driver=vsphere --name=$HOST_VOL_NAME -o size=${HOST_NODE_VOL_SIZE}
+    ./docker-env volume create --driver=vsphere --name=$HOST_VOL_NAME -o size=${HOST_NODE_VOL_SIZE} -o fstype=ext4
   done
   echo 
 
   STACK_FOLDER=${STACK_FOLDER}/vdvs
 
+  echo "MariaDB Galera Service Configuration:"
+  echo "-------------------------------------"
+
+  ./docker-env stack deploy -c ${STACK_FOLDER}/mariadb-galera.yml $STACK_NAME
+  if [ $? -ne 0 ]; then
+    echo "Failure deploying mariadb galera master stack"
+    exit 1
+  fi
+  echo "Waiting 2m for the galera seed node to start up"
+  sleep 120s
+
+  ./docker-env service scale ${STACK_NAME}_galera-node1=1
+  ./docker-env service scale ${STACK_NAME}_galera-node2=1
+  ./docker-env service scale ${STACK_NAME}_galera-node3=1
+  if [ $? -ne 0 ]; then
+    echo "Failure scaling up remaining galera-node containers"
+    exit 1
+  fi
+  echo "Waiting 4m for galera nodes 1, 2 & 3 to start up"
+  sleep 240s
+
+  echo "Scaling down seed node"
+  ./docker-env service scale ${STACK_NAME}_galera-seed=0
+  sleep 10s
+  echo "Removing seed node vDVS volume"
+  ./docker-env volume rm ${STACK_NAME}_galera-seed-volume@${HOST_NODE_DATASTORE}
+  sleep 30s
+  echo "Removing seed node"
+  ./docker-env service rm ${STACK_NAME}_galera-seed
+  sleep 10s
+
 else 
+
   echo "Host Data Stack Configuration:"
   echo "------------------------------"
   echo "Host Node 1: ${GALERA_NODE1}"
@@ -65,37 +101,33 @@ else
   ssh $SSH_USER@$GALERA_NODE1 "${SSH_BECOME} bash -s -- " < util/make-data-vol 1
   ssh $SSH_USER@$GALERA_NODE2 "${SSH_BECOME} bash -s -- " < util/make-data-vol 2
   ssh $SSH_USER@$GALERA_NODE3 "${SSH_BECOME} bash -s -- " < util/make-data-vol 3
-fi
 
-echo "Deploying the cluster network: ${GALERA_NETWORK_NAME} ${GALERA_NETWORK} ..."
-./docker-env network create --driver overlay --subnet $GALERA_NETWORK $GALERA_NETWORK_NAME
-echo
-echo "Deploying the MariaDB Galera ${STACK_NAME} cluster..."
+  ./docker-env stack deploy -c ${STACK_FOLDER}/mariadb-galera.yml $STACK_NAME
+  if [ $? -ne 0 ]; then
+    echo "Failure deploying mariadb galera master stack"
+    exit 1
+  fi
+  echo "Waiting 90s for the galera seed node to start up"
+  sleep 90s
 
-./docker-env stack deploy -c ${STACK_FOLDER}/mariadb-galera.yml $STACK_NAME
-if [ $? -ne 0 ]; then
-  echo "Failure deploying mariadb galera master stack"
-  exit 1
-fi
-echo "Waiting 90s for the galera master node to start up"
-sleep 90s
+  ./docker-env service scale ${STACK_NAME}_galera-node2=1
+  ./docker-env service scale ${STACK_NAME}_galera-node3=1
+  if [ $? -ne 0 ]; then
+    echo "Failure scaling up remaining galera-node containers"
+    exit 1
+  fi
+  echo "Waiting 3m for galera nodes 2 & 3 to start up"
+  sleep 180ss
 
-./docker-env service scale ${STACK_NAME}_galera-node2=1
-./docker-env service scale ${STACK_NAME}_galera-node3=1
-if [ $? -ne 0 ]; then
-  echo "Failure scaling up remaining galera-node containers"
-  exit 1
+  ./docker-env stack deploy -c ${STACK_FOLDER}/mariadb-galera-nodify-master.yml $STACK_NAME
+  if [ $? -ne 0 ]; then
+    echo "Failure nodifying the master galera instance with the node command"
+    exit 1
+  fi
+  echo "Waiting 90s for the galera master to nodify (it might take 2 or more cycles)"
+  sleep 90s
+  
 fi
-echo "Waiting 120s for the galera worker nodes to start up"
-sleep 120s
-
-./docker-env stack deploy -c ${STACK_FOLDER}/mariadb-galera-nodify-master.yml $STACK_NAME
-if [ $? -ne 0 ]; then
-  echo "Failure nodifying the master galera instance with the node command"
-  exit 1
-fi
-echo "Waiting 90s for the galera master to nodify (it might take 2 or more cycles)"
-sleep 90s
 
 ./docker-env service scale ${STACK_NAME}_galera-haproxy=1
 echo "Waiting 30s for the galera haproxy to startup"
diff --git a/swarm/docker-env b/swarm/docker-env
--- a/swarm/docker-env
+++ b/swarm/docker-env
@@ -1,17 +1,22 @@
 #!/bin/bash
 
-if [ ! -f ./api-certs/cert.pem ]; then
-  echo
-  echo "Can't find the api-certs required to connect to the swarm manager api!"
-  echo "Please ensure that the following certificats exist in the api-certs folder:"
-  echo 
-  echo "ca.pem"
-  echo "cert.pem"
-  echo "key.pem"
-  echo
-  echo "Note: These are generated by cluster-builder during swarm creation."
-  echo
-  exit 1
+if [ -z $DOCKER_CERT_PATH ]; then
+  echo "Using default legacy certificate path... soon to be deprecated!!!"
+  export DOCKER_CERT_PATH=./api-certs
+
+  if [ ! -f ./api-certs/cert.pem ]; then
+    echo
+    echo "Can't find the api-certs required to connect to the swarm manager api!"
+    echo "Please ensure that the following certificats exist in the api-certs folder:"
+    echo 
+    echo "ca.pem"
+    echo "cert.pem"
+    echo "key.pem"
+    echo
+    echo "Note: These are generated by cluster-builder during swarm creation."
+    echo
+    exit 1
+  fi
 fi
 
 if [ -z $DOCKER_HOST ]; then 
@@ -21,7 +26,6 @@ if [ -z $DOCKER_HOST ]; then
   exit 1
 fi
 
-export DOCKER_CERT_PATH=./api-certs
 export DOCKER_TLS_VERIFY=1
 
 docker $@
