fixed up image references

diff --git a/swarm/docker-env b/swarm/docker-env
--- a/swarm/docker-env
+++ b/swarm/docker-env
@@ -3,20 +3,20 @@
 if [ -z $DOCKER_CERT_PATH ]; then
   echo "Using default legacy certificate path... soon to be deprecated!!!"
   export DOCKER_CERT_PATH=./api-certs
+fi
 
-  if [ ! -f ./api-certs/cert.pem ]; then
-    echo
-    echo "Can't find the api-certs required to connect to the swarm manager api!"
-    echo "Please ensure that the following certificats exist in the api-certs folder:"
-    echo 
-    echo "ca.pem"
-    echo "cert.pem"
-    echo "key.pem"
-    echo
-    echo "Note: These are generated by cluster-builder during swarm creation."
-    echo
-    exit 1
-  fi
+if [ ! -f $DOCKER_CERT_PATH/cert.pem ]; then
+  echo
+  echo "Can't find the api-certs required to connect to the swarm manager api!"
+  echo "Please ensure that the following certificates exist in the specified docker-host-cert-path folder:"
+  echo 
+  echo "ca.pem"
+  echo "cert.pem"
+  echo "key.pem"
+  echo
+  echo "Note: These are generated by cluster-builder during CE swarm creation, or downloaded through the EE UCP."
+  echo
+  exit 1
 fi
 
 if [ -z $DOCKER_HOST ]; then 
